// buf.readDoubleBE(offset[, noAssert])
// buf.readDoubleLE(offset[, noAssert])
// buf.readFloatBE(offset[, noAssert])
// buf.readFloatLE(offset[, noAssert])
// buf.readInt8(offset[, noAssert])
// buf.readInt16BE(offset[, noAssert])
// buf.readInt16LE(offset[, noAssert])
// buf.readInt32BE(offset[, noAssert])
// buf.readInt32LE(offset[, noAssert])
// buf.readIntBE(offset, byteLength[, noAssert])
// buf.readIntLE(offset, byteLength[, noAssert])
// buf.readUInt8(offset[, noAssert])
// buf.readUInt16BE(offset[, noAssert])
// buf.readUInt16LE(offset[, noAssert])
// buf.readUInt32BE(offset[, noAssert])
// buf.readUInt32LE(offset[, noAssert])
// buf.readUIntBE(offset, byteLength[, noAssert])
// buf.readUIntLE(offset, byteLength[, noAssert])

// buf.write(string[, offset[, length]][, encoding])
// buf.writeDoubleBE(value, offset[, noAssert])
// buf.writeDoubleLE(value, offset[, noAssert])
// buf.writeFloatBE(value, offset[, noAssert])
// buf.writeFloatLE(value, offset[, noAssert])
// buf.writeInt8(value, offset[, noAssert])
// buf.writeInt16BE(value, offset[, noAssert])
// buf.writeInt16LE(value, offset[, noAssert])
// buf.writeInt32BE(value, offset[, noAssert])
// buf.writeInt32LE(value, offset[, noAssert])
// buf.writeIntBE(value, offset, byteLength[, noAssert])
// buf.writeIntLE(value, offset, byteLength[, noAssert])
// buf.writeUInt8(value, offset[, noAssert])
// buf.writeUInt16BE(value, offset[, noAssert])
// buf.writeUInt16LE(value, offset[, noAssert])
// buf.writeUInt32BE(value, offset[, noAssert])
// buf.writeUInt32LE(value, offset[, noAssert])
// buf.writeUIntBE(value, offset, byteLength[, noAssert])
// buf.writeUIntLE(value, offset, byteLength[, noAssert])

// BE: 大端序, LE: 小端序
// write: 写入, read: 读取